### ISSUE TITLE
Search tier names change

### ISSUE THREAD

**Issue by maksymilian-dabkowski** [BrownCLPS/LingView#24]
Different tiers display on the A'ingae and Yucatec Maya websites. What is going on? And what are the T1, T2, T3, etc. tiers? Could they be renamed something more informative?
![image](https://user-images.githubusercontent.com/23284227/85907623-10c31880-b7e0-11ea-88ec-ec92e4f4c9ad.png)
![image (1)](https://user-images.githubusercontent.com/23284227/85907625-115baf00-b7e0-11ea-85d3-af98b50c8ee8.png)

UPDATE: In an old issue, Thomas said the following:
> Don't know what the format for the tiers will be so I just put checkboxes for T1-T10. Once we know that, we can customize the tier selectors. Ideally, this would be done without hardcoding in the checkboxes (what I did for the short term)

Perhaps this is useful?

**Comment by sciepsilon** [comment]
Not sure if related: There was a period of time when LingView named the tier checkboxes T1, T2, T3, etc on the story page. Now LingView uses the tier names from the ELAN file, if available, or gives FLEx tiers meaningful names based on language and content type, like "English morph gloss" or "Spanish word", but internally it still uses T1, T2, etc in the json files that are created when uploading a FLEx or ELAN file. 

On the search page, the checkboxes should presumably be all the tier names that appear in any story on the site. Thus, different websites will have different tier names showing up. Displaying the correct checkbox labels can be accomplished by putting a list of the tier names in the search_index.json file, and then having React read that list of tier names while building the page. Maybe we do this already (but incorrectly), I don't know. 

I'm not sure what logic the Search feature uses to search in only the indicated tiers. I haven't tested it, so for all I know, maybe it currently ignores the user's tier selection entirely. Anyways, if we change how tiers are displayed on the search page, we might also need to change the search logic to make sure it can still use the tier information correctly. This change might be easy, or it might require restructuring some of LingView's data processing, changing the format of search_index.json, etc. which could take a few weeks.

**Comment by sciepsilon** [comment]
This will be fixed in my upcoming "fix-search" PR. It turns out we were actually formatting tier info differently in the json files from ELAN vs. FLEx. The search code assumed everything was handled like ELAN, so it was messing up on FLEx files.
