### ISSUE TITLE
Trilingualism

### ISSUE THREAD

**Issue by maksymilian-dabkowski** [BrownCLPS/LingView#28]
Implement trilingualism.

Probably best implemented as a website-wide feature, i.e. once selected, the correct language will stay consistent across all pages, be it About, Resource, Glossing conventions, etc.

**Comment by sciepsilon** [comment]
Basic version: change the language on all walls of text where we currently have multiple translations. (i.e. the content of the About, Resources, Glossing conventions pages and maybe another page or two that I'm missing). Once that works, it would be nice to also affect the language of UI text like the search button, the nav bar at the top of the site, and so on. Eventually it might be nice to auto-hide certain tiers on the stories page based on language preference, but this is more of a long shot and it shouldn't be part of version 1.
