### ISSUE TITLE
Set up GitHub Actions for edit.js

### ISSUE THREAD

**Issue by maksymilian-dabkowski** [BrownCLPS/LingView#39]

**Comment by sciepsilon** [comment]
Might be impossible, or might take about a week. Jacob writes (copied from his personal to-do list): 
4. get preprocessing/edit.js working through the browser
- *idea:* Make a runnable action, "Open Shell", that uses [https://github.com/mxschmitt/action-tmate](https://github.com/csexton/debugger-action) to allow a GH collaborator to run the preprocessing scripts interactively on a fresh clone of the master branch (where the stories are kept) (ppl should treat the tmate url like a password! it allows for unrestricted modification of the stories metadata)—after this step, automatically add, commit, and push the changes (then automatically re-deploy the website [if anything has changed]?)

**Comment by hollyyuqizheng** [comment]
Please see the "Edit Story Metadata" action. The instruction of using it is in the Wiki, under "metadata" page.
