### ISSUE TITLE
The string "undefined" shows up in some places

### ISSUE THREAD

**Issue by maksymilian-dabkowski** [BrownCLPS/LingView#40]
![image](https://user-images.githubusercontent.com/23284227/86609245-b2353180-bf79-11ea-8fcb-d2c830cf2b2c.png)

**Comment by sciepsilon** [comment]
Probably an hour or so to fix. Look at the preprocessing function that puts flex words together into a sentence.

**Comment by hollyyuqizheng** [comment]
Fixed by PR #50
