### ISSUE TITLE
Bottom search result are irrelevant to searched terms

### ISSUE THREAD

**Issue by maksymilian-dabkowski** [BrownCLPS/LingView#41]
The first couple of results are relevant to search terms:

![image](https://user-images.githubusercontent.com/23284227/86609323-d0029680-bf79-11ea-8ff5-0d1ddae9efc5.png)

But later results have nothing to do with the searched term:

![image](https://user-images.githubusercontent.com/23284227/86609462-f6c0cd00-bf79-11ea-9fb9-31ed26089eef.png)

For example, in the results above the string _nakhû_ does not appear anywhere

**Comment by sciepsilon** [comment]
Maybe the search has a "fuzziness" parameter that can be tuned to require only exact matches, or to allow near-exact matches? The fix is probably just a few lines of code, but it might take a while to figure out what those lines are.

**Comment by sciepsilon** [comment]
Closed in #58. I've set it to still be slightly fuzzy, so for example "afaye" matches "afaya" and "sembro" matches "sembrio". If desired, I can easily change it to show exact matches only.
