### ISSUE TITLE
Search result should link to specific sentence

### ISSUE THREAD

**Issue by sciepsilon** [BrownCLPS/LingView#60]
Search already links to a specific sentence if it's timed, we just need to mimic that behavior when the sentence comes from an untimed document. 

![image](https://user-images.githubusercontent.com/19783656/95559823-36f67800-09cd-11eb-9512-210b46b97578.png)

~~I recommend doing this~~ You could do this by modifying `preprocess_flex.js` to include a "sentence_number" property on each untimed sentence. Then if needed, modify `build_search.js` to make sure that property is included in `search_index.json`. For consistency, we should also refactor our untimed story display to use the "sentence_number" property. 

An alternate option would be for `build_search.js` to create the "sentence_number" property. In that case, the property would appear in `search_index.json`, but not in the individual json files for each story. ~~This works, but I think it's less consistent and would be more confusing to maintain.~~

**Comment by sciepsilon** [comment]
(Aaactually, I'm not convinced that one approach is better than another. Go ahead and do whichever you prefer.)

**Comment by hollyyuqizheng** [comment]
#68
