### ISSUE TITLE
Fix: search not returning all matches

### ISSUE THREAD

**Issue by sciepsilon** [BrownCLPS/LingView#96]
This issue was raised by Wyatt. Not sure what the exact problem is, need to diagnose. Possible fixes: option to turn off fuzzy search; option to see a second page of results instead of just returning the top N matches

**Comment by sciepsilon** [comment]
Right now looks like we cut it off at 25 search results

**Comment by hollyyuqizheng** [comment]
Yes, currently we are calling `slice(0,25)` on the fuse search result. Removing this bit does seem to allow all search results to be shown, but the list might be long, so we'd need a 'Next page' function to accompany the removal of slicing.

**Comment by hollyyuqizheng** [comment]
#97 has the fix.
